//////////////////////////////////////////////////////////////////////////////
//
// This file contains examples of a few different types of interfaces.
//
//////////////////////////////////////////////////////////////////////////////

record polarity-scores {
    compound: f64,
    positive: f64,
    negative: f64,
    neutral: f64,
}

sentiment: function(input: string) -> polarity-scores

//////////////////////////////////////////////////////////////////////////////

square: function(input: s32) -> s32

//////////////////////////////////////////////////////////////////////////////

record split-input {
    s: string,
    delimiter: string,
}

record split-output {
    c: string,
}

split: function(input: split-input) -> list<split-output>

//////////////////////////////////////////////////////////////////////////////

record hilbert-input {
    vec: list<u8>,
    min-value: f64,
    max-value: f64,
    scale: f64,
}

hilbert-encode: function(input: hilbert-input) -> string

